version: "2.1"
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    mem_limit: 805306368
    # mem_limit: 268435456
    ports:
      - "5601:5601"
    networks:
      - elastic-stack
    environment:
      ELASTICSEARCH_URL: http://localhost:9200
