version: "2"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    # mem_limit: 805306368
    mem_limit: 736870912
    # mem_limit: 268435456
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - elastic-stack
    # volumes:
    # - ./elasticsearch/es_data:/usr/share/elasticsearch/data
    # sysctls:
    # vm.max_map_count: 262144

  logstash:
    image: docker.elastic.co/logstash/logstash:7.0.0
    # mem_limit: 306870912
    mem_limit: 268435456
    ports:
      - "5044:5044"
    networks:
      - elastic-stack
    # volumes:
    # - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"

networks:
  elastic-stack:
